import { Injectable, Logger, OnApplicationShutdown, OnModuleInit } from '@nestjs/common';
import { ConfigService } from '@nestjs/config'; import { connect, AmqpConnectionManager, ChannelWrapper } from 'amqp-connection-manager'; import type { ConfirmChannel, ConsumeMessage } from 'amqplib';
export interface DomainEvent { event_id: string; event_type: string; source_service: string; entity_id: string; entity_version: number; schema_version: number; occurred_at: string; correlation_id: string; payload: Record<string, unknown>; }
type Handler = (event: DomainEvent) => Promise<void>; type Subscription = { queue: string; patterns: string[]; handler: Handler };
@Injectable()
export class EventsService implements OnModuleInit, OnApplicationShutdown {
  private readonly log = new Logger(EventsService.name); private connection?: AmqpConnectionManager; private publishChannel?: ChannelWrapper; private readonly consumers: ChannelWrapper[] = []; private readonly subs: Subscription[] = []; private connected = false;
  readonly exchange: string; private readonly url: string;
  constructor(config: ConfigService) { this.exchange = config.get<string>('RABBITMQ_EXCHANGE') ?? 'farmtotable.events'; this.url = config.get<string>('RABBITMQ_URL') ?? 'amqp://localhost:5672'; }
  onModuleInit(): void { this.connection = connect([this.url], { heartbeatIntervalInSeconds: 15 }); this.connection.on('connect', () => { this.connected = true; this.log.log('Conectado a RabbitMQ'); }); this.connection.on('disconnect', ({ err }) => { this.connected = false; this.log.warn(`RabbitMQ desconectado: ${err?.message ?? ''}`); }); this.publishChannel = this.connection.createChannel({ setup: (channel: ConfirmChannel) => channel.assertExchange(this.exchange, 'topic', { durable: true }) }); for (const sub of this.subs) this.start(sub); }
  isConnected(): boolean { return this.connected; }
  register(queue: string, patterns: string[], handler: Handler): void { const sub = { queue, patterns, handler }; this.subs.push(sub); if (this.connection) this.start(sub); }
  async publish(event: DomainEvent): Promise<void> { if (!this.publishChannel) throw new Error('RabbitMQ no inicializado'); await this.publishChannel.publish(this.exchange, event.event_type, Buffer.from(JSON.stringify(event)), { contentType: 'application/json', persistent: true, messageId: event.event_id, correlationId: event.correlation_id, type: event.event_type }); }
  private start(sub: Subscription): void { const dead = `${sub.queue}.dead`; const channel = this.connection!.createChannel({ setup: async (ch: ConfirmChannel) => { await ch.assertExchange(this.exchange, 'topic', { durable: true }); await ch.assertExchange(`${this.exchange}.dlx`, 'topic', { durable: true }); await ch.assertQueue(dead, { durable: true }); await ch.bindQueue(dead, `${this.exchange}.dlx`, sub.queue); await ch.assertQueue(sub.queue, { durable: true, deadLetterExchange: `${this.exchange}.dlx`, deadLetterRoutingKey: sub.queue }); for (const key of sub.patterns) await ch.bindQueue(sub.queue, this.exchange, key); await ch.prefetch(10); await ch.consume(sub.queue, (msg) => void this.handle(ch, sub, msg)); } }); this.consumers.push(channel); }
  private async handle(ch: ConfirmChannel, sub: Subscription, msg: ConsumeMessage | null): Promise<void> { if (!msg) return; try { const event = JSON.parse(msg.content.toString()) as DomainEvent; await sub.handler(event); ch.ack(msg); } catch (error) { this.log.error(`Fallo en ${sub.queue}: ${(error as Error).message}`); ch.nack(msg, false, !msg.fields.redelivered); } }
  async onApplicationShutdown(): Promise<void> { await Promise.allSettled(this.consumers.map((c) => c.close())); await this.publishChannel?.close(); await this.connection?.close(); }
}
